apiVersion: apps/v1
kind: Deployment
metadata:
  name: refty-infra-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: refty-infra-test
  template:
    metadata:
      labels:
        app: refty-infra-test
    spec:
      containers:
      - name: refty-infra-test
        image: ghcr.io/refty-yapi/refty-infra-test:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: LOG_LEVEL
          value: "info"
        - name: APP_VERSION
          value: "1.0.0"
        - name: REPOSITORY_URL
          valueFrom:
            secretKeyRef:
              name: refty-infra-test-secrets
              key: repository-url
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: refty-infra-test-secrets
              key: api-key
        - name: BRANCH
          value: "main"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5 